steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'global-docker.pkg.dev/crafty-isotope-354114/chatApi/chatApi:$COMMIT_SHA', '.']
  id: Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'global-docker.pkg.dev/crafty-isotope-354114/chatApi/chatApi:$COMMIT_SHA']
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'my-csharp-service',
         '--image', 'global-docker.pkg.dev/crafty-isotope-354114/chatApi/chatApi:$COMMIT_SHA',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']
  id: Deploy
images:
- global-docker.pkg.dev/crafty-isotope-354114/chatApi/chatApi:$COMMIT_SHA